// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: timetracker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimeEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description string             `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Start       string             `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	Stop        string             `protobuf:"bytes,4,opt,name=stop,proto3" json:"stop,omitempty"`
	Tags        []string           `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Source      string             `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Client      *TimeEntry_Client  `protobuf:"bytes,7,opt,name=client,proto3" json:"client,omitempty"`
	Project     *TimeEntry_Project `protobuf:"bytes,8,opt,name=project,proto3" json:"project,omitempty"`
}

func (x *TimeEntry) Reset() {
	*x = TimeEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timetracker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeEntry) ProtoMessage() {}

func (x *TimeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_timetracker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeEntry.ProtoReflect.Descriptor instead.
func (*TimeEntry) Descriptor() ([]byte, []int) {
	return file_timetracker_proto_rawDescGZIP(), []int{0}
}

func (x *TimeEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TimeEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TimeEntry) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *TimeEntry) GetStop() string {
	if x != nil {
		return x.Stop
	}
	return ""
}

func (x *TimeEntry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TimeEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TimeEntry) GetClient() *TimeEntry_Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *TimeEntry) GetProject() *TimeEntry_Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type GetTimeEntriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*TimeEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *GetTimeEntriesResponse) Reset() {
	*x = GetTimeEntriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timetracker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTimeEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeEntriesResponse) ProtoMessage() {}

func (x *GetTimeEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timetracker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeEntriesResponse.ProtoReflect.Descriptor instead.
func (*GetTimeEntriesResponse) Descriptor() ([]byte, []int) {
	return file_timetracker_proto_rawDescGZIP(), []int{1}
}

func (x *GetTimeEntriesResponse) GetEntries() []*TimeEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetTimeEntriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start string `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	Stop  string `protobuf:"bytes,2,opt,name=stop,proto3" json:"stop,omitempty"`
}

func (x *GetTimeEntriesRequest) Reset() {
	*x = GetTimeEntriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timetracker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTimeEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeEntriesRequest) ProtoMessage() {}

func (x *GetTimeEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timetracker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeEntriesRequest.ProtoReflect.Descriptor instead.
func (*GetTimeEntriesRequest) Descriptor() ([]byte, []int) {
	return file_timetracker_proto_rawDescGZIP(), []int{2}
}

func (x *GetTimeEntriesRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *GetTimeEntriesRequest) GetStop() string {
	if x != nil {
		return x.Stop
	}
	return ""
}

type TimeEntry_Client struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TimeEntry_Client) Reset() {
	*x = TimeEntry_Client{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timetracker_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeEntry_Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeEntry_Client) ProtoMessage() {}

func (x *TimeEntry_Client) ProtoReflect() protoreflect.Message {
	mi := &file_timetracker_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeEntry_Client.ProtoReflect.Descriptor instead.
func (*TimeEntry_Client) Descriptor() ([]byte, []int) {
	return file_timetracker_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TimeEntry_Client) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TimeEntry_Client) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TimeEntry_Project struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TimeEntry_Project) Reset() {
	*x = TimeEntry_Project{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timetracker_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeEntry_Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeEntry_Project) ProtoMessage() {}

func (x *TimeEntry_Project) ProtoReflect() protoreflect.Message {
	mi := &file_timetracker_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeEntry_Project.ProtoReflect.Descriptor instead.
func (*TimeEntry_Project) Descriptor() ([]byte, []int) {
	return file_timetracker_proto_rawDescGZIP(), []int{0, 1}
}

func (x *TimeEntry_Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TimeEntry_Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_timetracker_proto protoreflect.FileDescriptor

var file_timetracker_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72,
	0x22, 0xe1, 0x02, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61,
	0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x65, 0x72, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x38, 0x0a,
	0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x1a, 0x2c, 0x0a, 0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x2d, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4a, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x45,
	0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30,
	0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x22, 0x41, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73,
	0x74, 0x6f, 0x70, 0x32, 0x68, 0x0a, 0x0b, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x72, 0x61, 0x63, 0x6b,
	0x65, 0x72, 0x12, 0x59, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x12, 0x22, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x74,
	0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_timetracker_proto_rawDescOnce sync.Once
	file_timetracker_proto_rawDescData = file_timetracker_proto_rawDesc
)

func file_timetracker_proto_rawDescGZIP() []byte {
	file_timetracker_proto_rawDescOnce.Do(func() {
		file_timetracker_proto_rawDescData = protoimpl.X.CompressGZIP(file_timetracker_proto_rawDescData)
	})
	return file_timetracker_proto_rawDescData
}

var file_timetracker_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_timetracker_proto_goTypes = []interface{}{
	(*TimeEntry)(nil),              // 0: timetracker.TimeEntry
	(*GetTimeEntriesResponse)(nil), // 1: timetracker.GetTimeEntriesResponse
	(*GetTimeEntriesRequest)(nil),  // 2: timetracker.GetTimeEntriesRequest
	(*TimeEntry_Client)(nil),       // 3: timetracker.TimeEntry.Client
	(*TimeEntry_Project)(nil),      // 4: timetracker.TimeEntry.Project
}
var file_timetracker_proto_depIdxs = []int32{
	3, // 0: timetracker.TimeEntry.client:type_name -> timetracker.TimeEntry.Client
	4, // 1: timetracker.TimeEntry.project:type_name -> timetracker.TimeEntry.Project
	0, // 2: timetracker.GetTimeEntriesResponse.entries:type_name -> timetracker.TimeEntry
	2, // 3: timetracker.TimeTracker.GetTimeEntries:input_type -> timetracker.GetTimeEntriesRequest
	1, // 4: timetracker.TimeTracker.GetTimeEntries:output_type -> timetracker.GetTimeEntriesResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_timetracker_proto_init() }
func file_timetracker_proto_init() {
	if File_timetracker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_timetracker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timetracker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTimeEntriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timetracker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTimeEntriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timetracker_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeEntry_Client); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timetracker_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeEntry_Project); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_timetracker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_timetracker_proto_goTypes,
		DependencyIndexes: file_timetracker_proto_depIdxs,
		MessageInfos:      file_timetracker_proto_msgTypes,
	}.Build()
	File_timetracker_proto = out.File
	file_timetracker_proto_rawDesc = nil
	file_timetracker_proto_goTypes = nil
	file_timetracker_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TimeTrackerClient is the client API for TimeTracker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TimeTrackerClient interface {
	GetTimeEntries(ctx context.Context, in *GetTimeEntriesRequest, opts ...grpc.CallOption) (*GetTimeEntriesResponse, error)
}

type timeTrackerClient struct {
	cc grpc.ClientConnInterface
}

func NewTimeTrackerClient(cc grpc.ClientConnInterface) TimeTrackerClient {
	return &timeTrackerClient{cc}
}

func (c *timeTrackerClient) GetTimeEntries(ctx context.Context, in *GetTimeEntriesRequest, opts ...grpc.CallOption) (*GetTimeEntriesResponse, error) {
	out := new(GetTimeEntriesResponse)
	err := c.cc.Invoke(ctx, "/timetracker.TimeTracker/GetTimeEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimeTrackerServer is the server API for TimeTracker service.
type TimeTrackerServer interface {
	GetTimeEntries(context.Context, *GetTimeEntriesRequest) (*GetTimeEntriesResponse, error)
}

// UnimplementedTimeTrackerServer can be embedded to have forward compatible implementations.
type UnimplementedTimeTrackerServer struct {
}

func (*UnimplementedTimeTrackerServer) GetTimeEntries(context.Context, *GetTimeEntriesRequest) (*GetTimeEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTimeEntries not implemented")
}

func RegisterTimeTrackerServer(s *grpc.Server, srv TimeTrackerServer) {
	s.RegisterService(&_TimeTracker_serviceDesc, srv)
}

func _TimeTracker_GetTimeEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimeEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeTrackerServer).GetTimeEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timetracker.TimeTracker/GetTimeEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeTrackerServer).GetTimeEntries(ctx, req.(*GetTimeEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TimeTracker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "timetracker.TimeTracker",
	HandlerType: (*TimeTrackerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTimeEntries",
			Handler:    _TimeTracker_GetTimeEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "timetracker.proto",
}
